### PR TITLE
Adding workflow for publishing to docker hub

### PR DESCRIPTION
**Pull request by treyrich**
This related to [1000](https://github.com/tagyoureit/nodejs-poolController/pull/1000) and it separating the existing docker workflow there.

This should not be merged until the docker image name is reviewed and approved.

### CODE REVIEW

**Review by tagyoureit — APPROVED** [review]

**Comment by treyrich** [comment]
Assuming the secrets are in place and the repo has been created, this should be good to go I think.

**Comment by tagyoureit** [comment]
Do I need to give him (@rstrouse) a token for the tagyoureit/njspc-dashpanel repo?  Or create an account for him on my docker?

**Comment by treyrich** [comment]
Looks like this failed because the secrets weren’t in place.

**Comment by treyrich** [comment]
> Do I need to give him (@rstrouse) a token for the tagyoureit/njspc-dashpanel repo? Or create an account for him on my docker?

A token is all that’s required, but I guess it depends on how trusted this repo/owner is to you. 

Alternatively we could publish this to a docker repo @rstrouse owns as well.

**Comment by tagyoureit** [comment]
I've met him in person, and looked him in the eye... he's trustworthy.

**Pull request merged**
